import { describe, expect, it } from 'vitest'
import { Options } from '../dist/types'
import { search } from '../dist/index'

const options: Options = {
  include: ['src/**/*'],
  search: [/searcH/i, 'search']
}

describe('search', () => {
  it('text', async () => {
    const matches = await search(options)
    matches.forEach(match => match.file = '.' + match.file.replace(process.cwd(), ''))
    const files = new Set(matches.map(t => t.file))
    const matchCount = matches.length
    expect(files.size).toMatchInlineSnapshot('3')
    expect(matchCount).toMatchInlineSnapshot('54')
    expect(matches).toMatchInlineSnapshot(`
      [
        {
          "end": 225,
          "file": "./src/index.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 219,
        },
        {
          "end": 376,
          "file": "./src/index.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 370,
        },
        {
          "end": 514,
          "file": "./src/index.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 508,
        },
        {
          "end": 530,
          "file": "./src/index.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 524,
        },
        {
          "end": 225,
          "file": "./src/index.ts",
          "match": "search",
          "search": "search",
          "start": 219,
        },
        {
          "end": 376,
          "file": "./src/index.ts",
          "match": "search",
          "search": "search",
          "start": 370,
        },
        {
          "end": 514,
          "file": "./src/index.ts",
          "match": "search",
          "search": "search",
          "start": 508,
        },
        {
          "end": 530,
          "file": "./src/index.ts",
          "match": "search",
          "search": "search",
          "start": 524,
        },
        {
          "end": 72,
          "file": "./src/types.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 66,
        },
        {
          "end": 80,
          "file": "./src/types.ts",
          "match": "Search",
          "search": /searcH/i,
          "start": 74,
        },
        {
          "end": 147,
          "file": "./src/types.ts",
          "match": "Search",
          "search": /searcH/i,
          "start": 141,
        },
        {
          "end": 200,
          "file": "./src/types.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 194,
        },
        {
          "end": 208,
          "file": "./src/types.ts",
          "match": "Search",
          "search": /searcH/i,
          "start": 202,
        },
        {
          "end": 72,
          "file": "./src/types.ts",
          "match": "search",
          "search": "search",
          "start": 66,
        },
        {
          "end": 200,
          "file": "./src/types.ts",
          "match": "search",
          "search": "search",
          "start": 194,
        },
        {
          "end": 51,
          "file": "./src/worker.ts",
          "match": "Search",
          "search": /searcH/i,
          "start": 45,
        },
        {
          "end": 92,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 86,
        },
        {
          "end": 123,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 117,
        },
        {
          "end": 131,
          "file": "./src/worker.ts",
          "match": "Search",
          "search": /searcH/i,
          "start": 125,
        },
        {
          "end": 172,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 166,
        },
        {
          "end": 191,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 185,
        },
        {
          "end": 229,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 223,
        },
        {
          "end": 260,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 254,
        },
        {
          "end": 275,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 269,
        },
        {
          "end": 291,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 285,
        },
        {
          "end": 306,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 300,
        },
        {
          "end": 386,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 380,
        },
        {
          "end": 425,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 419,
        },
        {
          "end": 581,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 575,
        },
        {
          "end": 617,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 611,
        },
        {
          "end": 625,
          "file": "./src/worker.ts",
          "match": "Search",
          "search": /searcH/i,
          "start": 619,
        },
        {
          "end": 673,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 667,
        },
        {
          "end": 761,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 755,
        },
        {
          "end": 777,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 771,
        },
        {
          "end": 787,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 781,
        },
        {
          "end": 810,
          "file": "./src/worker.ts",
          "match": "search",
          "search": /searcH/i,
          "start": 804,
        },
        {
          "end": 92,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 86,
        },
        {
          "end": 123,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 117,
        },
        {
          "end": 172,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 166,
        },
        {
          "end": 191,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 185,
        },
        {
          "end": 229,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 223,
        },
        {
          "end": 260,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 254,
        },
        {
          "end": 275,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 269,
        },
        {
          "end": 291,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 285,
        },
        {
          "end": 306,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 300,
        },
        {
          "end": 386,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 380,
        },
        {
          "end": 425,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 419,
        },
        {
          "end": 581,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 575,
        },
        {
          "end": 617,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 611,
        },
        {
          "end": 673,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 667,
        },
        {
          "end": 761,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 755,
        },
        {
          "end": 777,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 771,
        },
        {
          "end": 787,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 781,
        },
        {
          "end": 810,
          "file": "./src/worker.ts",
          "match": "search",
          "search": "search",
          "start": 804,
        },
      ]
    `)
  })
})
